// Type declarations for WASM module (auto-generated by wasm-pack)
declare module 'book-creation-wasm' {
  export function cache_image(id: string, data: Uint8Array): void;
  export function clear_image_cache(): void;
  export function create_document_from_pages(pages_js: unknown, width: number, height: number): unknown;
  export function export_bookproj(pages_js: unknown, metadata_js: unknown): Uint8Array;
  export function export_docx(pages_js: unknown, metadata_js: unknown): Uint8Array;
  export function get_image(id: string): Uint8Array | undefined;
  export function init(): void;
  export function load_project(data: Uint8Array): unknown;
  export function parse_docx(data: Uint8Array): unknown;
  export function process_pdf_page(page_data: unknown): unknown;
  export function save_project(project_js: unknown): Uint8Array;
  export function update_layer(layer_js: unknown, updates_js: unknown): unknown;
  
  type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;
  export default function __wbg_init(input?: InitInput | Promise<InitInput>): Promise<unknown>;
}
